---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
  amd64: ghcr.io/home-assistant/amd64-base:latest
  armv7: ghcr.io/home-assistant/armv7-base:latest
codenotary:
  base_image: codenotary@frenck.dev
  signer: codenotary@frenck.dev